### PR TITLE
feat(plugins): split client and server plugin entries

### PR DESCRIPTION
**Pull request by boudra**
### Linked issue

#4192 supplied the timeline and slash-command base and is merged on `main`. No standalone issue.

### Why

Plugin authors currently mix client callbacks and server handlers in one entry while the compiler strips registrations by method name. Explicit client and server entries make ownership visible, enforce runtime boundaries, and give every client registration one lifecycle.

### Phase 1 — compiler and runtime

- Resolve `index.client.ts(x)` and `index.server.ts(x)` independently; require at least one and reject legacy-only roots with the migration URL.
- Compile each target from its own entry and remove registration-name stripping.
- Enforce directory-only boundaries: code belongs under `client/`, `server/`, or `shared/`; other root modules fail with `Plugin modules belong in client/, server/, or shared/`.
- Reject client-to-server, server-to-client, shared-to-runtime, and client `node:` imports at compile time.
- Classify esbuild's canonical resolved path, allowing dependency internals under in-root `node_modules` while rejecting dependency escapes and symlinks into the wrong runtime or outside the plugin root.

Gate evidence:

- `compiler.test.ts`: 23 passed, including root, relative escape, absolute escape, escaped `node_modules`, dependency-relative runtime escape, relative and bare-package symlink-target rejection, ancestor-manifest and remembered-root bypass rejection, and valid linked dependencies; nested directory resolution; client `node:` rejection; and valid dependency-internal relative imports.
- `runtime.posix.test.ts`: 24 passed; `index.posix.test.ts`: 15 passed; `managed-source.posix.test.ts`: 2 passed; `bootstrap.smoke.test.ts`: 21 passed.
- CLI lifecycle standalone runner passed after the required `npm run build:server` refresh.

### Phase 2 — plugin package and app runner

- Add `PluginServerContext`; make `PluginClientContext` own all client registrations; rename `addClientSlashCommand` to `addSlashCommand`; remove `PluginContext` and `addClientSide`.
- Collapse client evaluation/startup into `runPluginClientBundle`; move app runtime construction to `plugins/client-runtime.ts`.
- Suppress setup-time change notifications and publish once after an installation is stored; late changes still publish live. Cleanup remains entry-first with idempotent removers.
- Export `defineRpc`, `defineAttachmentSource`, `RpcInput`, and `RpcOutput` from `@getpaseo/plugin`. Keep `@getpaseo/plugin/server` for handler-only types such as `PluginHandlerContext`.
- Migrate package specifier allowlists, runtime injection, fixtures, and all five examples.

Gate evidence:

- App tests passed individually from `packages/app`: evaluator 21, client runtime 2, registry 11, and every other touched registry/contribution/timeline/panel test.
- Plugin host tests: 6 passed. Plugin Paseo API E2E: 2 passed. Linear and timeline example tests: 4 passed each.
- Focused Playwright files passed individually: plugin host UI, management, theme, and workspace panels (1 each).
- On the isolated worktree daemon at `127.0.0.1:16768`, catppuccin, inline-thinking, linear, local-plugin, and timeline-items were reloaded and each reported `running`. The daemon was then stopped.

### Phase 3 — scaffold

- Generate explicit entries plus `client/`, `server/`, and `shared/` modules.
- Omit `DOM` from `tsconfig.lib` and restrict ambient `types` to React; generated and repository examples typecheck with React Native, TanStack Query, and Zod types.
- Generate `client/web.ts` without a triple-slash DOM reference. It declares only its module-local `window.open` shape, gates the web path with `Platform.OS === "web"`, and uses `Linking.openURL` on native; the surface calls `openExternal`.
- Use root SDK contract helpers and `RpcInput` in generated shared/server code.

Gate evidence:

- `scaffold.test.ts`: 3 passed. It runs the real TypeScript CLI in fresh processes, proves the generated project compiles, then appends `document.title = "x"` to `client/greeting.tsx` and proves compilation fails with `Cannot find name 'document'`.
- A fresh `paseo plugin init` scaffold typechecked against the worktree SDK and installed on the isolated daemon as `phase3-scaffold-mobile`; it reported `running`.
- No dependency required adding the DOM library back.

### Phase 4 — docs and skill

- Restore the full internal plugin guide and `paseo-plugin` skill, changing only the obsolete mixed-entry/suffix API and adding directory organization, root SDK imports, compile-error wording, and mobile checks.
- Keep every contribution section, runtime module table, install/build rules, trust procedure, host coalescing, verification flow, and failure table.
- Update example READMEs to the new entry/directory paths.
- Retain the standalone migration guide and its drift test. The reviewer completed the public-doc rewrite in commit `64af15eab` (rebased from `8e726a06a`), covering the new entries, directory-only organization, SDK imports, mobile guardrail, and mechanical migration.

Gate evidence:

- `migration-doc.test.ts`: 1 passed against the current reviewer-owned migration file.
- `rg` found no suffix-boundary instructions in owned docs, skill, code, or example READMEs.
- Diff audit against `986ad28ea`: removed `docs/plugins.md` and skill prose is limited to the old `index.ts`, suffix boundaries, registration stripping, `addClientSide`, `addClientSlashCommand`, and mixed `plugin.*` snippets; each was replaced in place. All unrelated paragraphs remain. Example README removals are old filenames only.

### Final QA

- After rebasing onto `main`, `npm install`, `npm run typecheck`, `npm run lint`, and `npm run format` passed with a clean worktree.
- Final focused tests passed individually: scaffold 3, compiler 23, server runtime 24, client runtime 2, evaluator 21, and migration-doc 1. The workspace observation file passed 41/41 in three consecutive runs.
- Every touched Vitest file passed individually. The four touched Playwright specs passed individually with their native runner. The standalone CLI lifecycle file passed with its TSX runner.
- Full local test suites were not run, per repository policy.
- iOS, Android, and Electron were not manually exercised. Mobile constraints are covered by the DOM-free example/scaffold typechecks, the real stray-`document` regression, React Native-only scaffold, Platform gate, and skill audit.
- Initial manual CI before review fixes failed: https://github.com/getpaseo/paseo/actions/runs/33616714385
- First post-fix manual CI reached 17/18 green; Windows first hit an unrelated terminal timing flake, then its isolated rerun exposed `EBUSY` in the new compiler fixture cleanup: https://github.com/getpaseo/paseo/actions/runs/33621029334
- The fixture cleanup now uses Node's Windows retry options. Fresh manual CI passed all 18 jobs: https://github.com/getpaseo/paseo/actions/runs/33624951493
- Earlier rebased-head CI exposed timing bugs fixed with state-based waits: repository watcher registration before emitting, visible sidebar rows before measurement (landed independently on `main`), and confirmed browser parking before inactive capture. The repository file passed 41/41 three consecutive times; sidebar Playwright passed 2/2; and the real desktop browser E2E passed twice locally with inactive capture.
- Mermaid streaming completion could remount the iframe between visibility and layout sampling. The helper now checks the real completion transition around measurement; the exact browser journey passed three consecutive local runs.
- The state-synchronization head passed pull-request CI, Nix/macOS, and Docker before the final security review: https://github.com/getpaseo/paseo/actions/runs/33643525456, https://github.com/getpaseo/paseo/actions/runs/33643525186, https://github.com/getpaseo/paseo/actions/runs/33643525379
- Final corrected-head CI passed — [standard](https://github.com/getpaseo/paseo/actions/runs/33656242665), [Docker](https://github.com/getpaseo/paseo/actions/runs/33656242723), [Nix/macOS](https://github.com/getpaseo/paseo/actions/runs/33656242940).

### Checklist

- [x] One focused change
- [x] Phased commits and fix-up commits
- [x] Focused local QA
- [x] Worktree daemon QA without touching port 6767
- [x] Rebased-head pull-request CI green

### CODE REVIEW

File: packages/server/src/server/plugins/compiler.ts [hunk 1]
```diff
@@ -71,193 +69,45 @@ function loadEsbuild(): typeof import("esbuild") {
...
-    throw new Error("Plugin default export must receive one named context parameter");
-  }
-  const body = Reflect.get(declaration, "body");
-  if (body === null || typeof body !== "object" || Reflect.get(body, "type") !== "BlockStatement") {
-    throw new Error("Plugin default export must have a block body");
-  }
-  return { body, contextName: String(Reflect.get(parameter, "name")) };
+function directoryTarget(filePath: string, pluginDirectory: string): PluginModuleLocation | null {
+  const relative = path.relative(pluginDirectory, filePath);
+  if (relative.startsWith("..") || path.isAbsolute(relative)) return null;
```
[the remark this answers is not in the document]
Comment (boudra) [reply packages/server/src/server/plugins/compiler.ts]: Fixed in 691caa015. Relative imports that escape the plugin root now classify as invalid, while any resolved path containing a node_modules segment remains exempt from plugin directory classification. Added a red-first compiler regression; compiler.test.ts passes 15/15.

File: packages/server/src/server/plugins/compiler.ts [hunk 2]
```diff
@@ -71,193 +69,45 @@ function loadEsbuild(): typeof import("esbuild") {
...
-  }
-  const body = Reflect.get(declaration, "body");
-  if (body === null || typeof body !== "object" || Reflect.get(body, "type") !== "BlockStatement") {
-    throw new Error("Plugin default export must have a block body");
-  }
-  return { body, contextName: String(Reflect.get(parameter, "name")) };
+function directoryTarget(filePath: string, pluginDirectory: string): PluginModuleLocation | null {
+  if (filePath.split(path.sep).includes("node_modules")) return null;
+  const relative = path.relative(pluginDirectory, filePath);
+  if (relative.startsWith("..") || path.isAbsolute(relative)) return "invalid";
```
[the remark this answers is not in the document]
Comment (boudra) [reply packages/server/src/server/plugins/compiler.ts:76]: Fixed in 86c5292e5. The node_modules exemption now keys off the importer path, so dependency-internal relative imports remain valid while plugin-authored escaped node_modules paths are rejected. Added a red-first regression; the existing dependency-internal fixture remains green.

File: packages/server/src/server/plugins/compiler.ts [hunk 3]
```diff
@@ -71,193 +69,45 @@ function loadEsbuild(): typeof import("esbuild") {
...
-function createRuntimeBoundaryPlugin(target: PluginBuildTarget): Plugin {
+function createRuntimeBoundaryPlugin(target: PluginBuildTarget, pluginDirectory: string): Plugin {
   return {
     name: `paseo-plugin-${target}-runtime-boundary`,
     setup(buildContext) {
-      buildContext.onResolve({ filter: /\.(?:client|server)(?:\.[cm]?[jt]sx?)?$/ }, (args) => {
-        const importedTarget = moduleTarget(args.path);
-        if (importedTarget === null || importedTarget === target) return null;
+      buildContext.onResolve({ filter: /.*/ }, (args) => {
+        if (args.kind === "entry-point" || !args.path.startsWith(".")) return null;
```
[the remark this answers is not in the document]
Comment (boudra) [reply packages/server/src/server/plugins/compiler.ts]: Fixed in 86c5292e5. Absolute filesystem imports now pass through directory classification and are rejected outside the plugin root or across runtime boundaries. Added a red-first regression.

File: packages/server/src/server/plugins/compiler.ts [hunk 4]
```diff
@@ -71,193 +69,46 @@ function loadEsbuild(): typeof import("esbuild") {
...
   return {
     name: `paseo-plugin-${target}-runtime-boundary`,
     setup(buildContext) {
-      buildContext.onResolve({ filter: /\.(?:client|server)(?:\.[cm]?[jt]sx?)?$/ }, (args) => {
-        const importedTarget = moduleTarget(args.path);
-        if (importedTarget === null || importedTarget === target) return null;
+      buildContext.onResolve({ filter: /.*/ }, (args) => {
+        if (args.kind === "entry-point") return null;
+        if (!args.path.startsWith(".") && !path.isAbsolute(args.path)) return null;
+        if (args.importer.split(path.sep).includes("node_modules")) return null;
```
[the remark this answers is not in the document]
Comment (boudra) [reply packages/server/src/server/plugins/compiler.ts]: Fixed. Relative imports are now classified from esbuild’s canonical resolution result instead of skipping dependency importers. A fixture dependency that escapes into server/ now fails client compilation, while internal node_modules client/ paths remain allowed. The focused compiler file passes 19/19.

File: packages/server/src/server/plugins/compiler.ts [hunk 5]
```diff
@@ -71,193 +69,46 @@ function loadEsbuild(): typeof import("esbuild") {
...
+        const resolvedPath = path.resolve(args.resolveDir, args.path);
+        const importedTarget = directoryTarget(resolvedPath, pluginDirectory);
```
[the remark this answers is not in the document]
Comment (boudra) [reply packages/server/src/server/plugins/compiler.ts]: Fixed at the same boundary. esbuild resolves symlinks before directory classification, so a client/ symlink targeting server/ is rejected. Added a focused symlink regression; the compiler file passes 19/19.

File: packages/server/src/server/plugins/compiler.ts [hunk 6]
```diff
@@ -71,193 +69,63 @@ function loadEsbuild(): typeof import("esbuild") {
...
+  const boundaryResolution = {};
   return {
     name: `paseo-plugin-${target}-runtime-boundary`,
     setup(buildContext) {
-      buildContext.onResolve({ filter: /\.(?:client|server)(?:\.[cm]?[jt]sx?)?$/ }, (args) => {
-        const importedTarget = moduleTarget(args.path);
-        if (importedTarget === null || importedTarget === target) return null;
+      buildContext.onResolve({ filter: /.*/ }, async (args) => {
+        if (args.kind === "entry-point") return null;
+        if (!args.path.startsWith(".") && !path.isAbsolute(args.path)) return null;
```
[the remark this answers is not in the document]
Comment (boudra) [reply packages/server/src/server/plugins/compiler.ts]: Fixed. Bare imports now go through esbuild canonical resolution too; configured SDK externals remain external, while a package entry symlinked into server/ is rejected from the client bundle. Added the red-first regression and the compiler file passes 20/20; typecheck, lint, and format are clean.

File: packages/server/src/server/plugins/compiler.ts [hunk 7]
```diff
@@ -71,193 +69,62 @@ function loadEsbuild(): typeof import("esbuild") {
...
+        if (
+          resolution.errors.length > 0 ||
+          resolution.external ||
+          resolution.namespace !== "file"
+        ) {
+          return null;
+        }
+        const resolvedPath = resolution.path;
+        const importedTarget = directoryTarget(resolvedPath, pluginDirectory);
+        if (importedTarget === "invalid") {
```
[the remark this answers is not in the document]
Comment (boudra) [reply packages/server/src/server/plugins/compiler.ts:188]: Fixed. Canonical paths outside the plugin are allowed only when the bare specifier resolves inside a package root whose manifest name matches that specifier; that root is then used for its internal relative imports. Imports leaving the linked package still hit containment/runtime checks. Added a red-first linked-package fixture; compiler tests pass 21/21 and typecheck, lint, and format are clean.

File: packages/server/src/server/plugins/compiler.ts [hunk 8]
```diff
@@ -71,193 +69,97 @@ function loadEsbuild(): typeof import("esbuild") {
...
-    if (typeof start !== "number" || typeof end !== "number") {
-      throw new Error(`Could not locate ${importedTarget}-only import in plugin entry point`);
+function findDependencyRoot(resolvedPath: string, specifier: string): string | null {
+  const expectedName = dependencyName(specifier);
+  let directory = path.dirname(resolvedPath);
+  for (;;) {
+    const manifestPath = path.join(directory, "package.json");
+    if (existsSync(manifestPath)) {
+      const manifest = JSON.parse(readFileSync(manifestPath, "utf8")) as { name?: unknown };
+      if (manifest.name === expectedName) return directory;
```
[the remark this answers is not in the document]
Comment (boudra) [reply packages/server/src/server/plugins/compiler.ts]: Fixed. A matching dependency manifest is rejected when its directory contains the plugin or is inside the plugin, so neither the plugin package nor an enclosing workspace can become an exempt linked root. Added the red-first ancestor-manifest fixture; valid disjoint linked packages still compile. Compiler tests pass 22/22 and typecheck, lint, and format are clean.

File: packages/server/src/server/plugins/compiler.ts [hunk 9]
```diff
@@ -71,193 +69,106 @@ function loadEsbuild(): typeof import("esbuild") {
...
+          resolution.external ||
+          resolution.namespace !== "file"
+        ) {
+          return null;
+        }
+        const resolvedPath = resolution.path;
+        const importedTarget = directoryTarget(resolvedPath, pluginDirectory);
+        if (importedTarget === "invalid") {
+          if ([...linkedDependencyRoots].some((root) => containsPath(root, resolvedPath)))
+            return null;
```
[the remark this answers is not in the document]
Comment (boudra) [reply packages/server/src/server/plugins/compiler.ts]: Fixed. Plugin-local lexical paths are checked before canonical linked-root exemptions, and a remembered root now applies only when both importer and resolved target are inside that root. Added the red-first plugin server symlink regression; compiler tests pass 23/23 and typecheck, lint, and format are clean.
